# Generated by Django 5.1.2 on 2024-10-31 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_dataset_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='textentry',
            name='is_tagged',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='textentry',
            name='categories',
            field=models.ManyToManyField(blank=True, to='api.category'),
        ),
    ]
