# Generated by Django 5.1.2 on 2024-10-31 15:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_textentry_is_tagged_alter_textentry_categories'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='textentry',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='textentry',
            name='tagged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='textentry',
            name='tagged_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='textentry',
            name='is_tagged',
            field=models.BooleanField(default=False),
        ),
    ]
